---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcrds.bonny-plug.ufirst.io
spec:
  group: bonny-plug.ufirst.io
  scope: Namespaced
  names:
    kind: TestCrd
    plural: testcrds
    singular: testcrd
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instance:
                  type: string
    - name: v2
      served: false
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instance:
                  type: string
      additionalPrinterColumns:
