---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrds.bonny-plug.ufirst.io
spec:
  group: bonny-plug.ufirst.io
  scope: Namespaced
  names:
    kind: TestCrd
    plural: testcrds
    singular: testcrd
  version: v1
